### ISSUE TITLE
错误的 endTime

### ISSUE THREAD

**Issue by sciooga** [justjavac/baby-time#2]
先恭喜，但是 BUG 还是要修修的
var endTime = new Date(now.getFullYear() + 18, 5, 7, 9); 
今年是 2017+18 明年就是 2018+18，截止时间是会变的...

**Comment by justjavac** [comment]
等我儿子/女儿出生后就发布 2.0 版

**Comment by dantangfan** [comment]
太凶残了。。

**Comment by lordbaby** [comment]
congratulation！

**Comment by justjavac** [comment]
@lordbaby 谢谢

**Comment by think2cat** [comment]
万一10年以后取消高考了，到时候15年义务教育 🎃
